### ISSUE TITLE
Enable PSU_CONTROL

### ISSUE THREAD

**Issue by c1000mg** [FLYmaker/FLY-CDY#1]
I was wondering if you could  release pin names layout in the board, for both Marlin and RepRap Firmware,
I'm trying to figure out how to configure a PSU Control in RepRap Firmware in the FLY-CDY.

I was also reading the **FLY-CDY Use tutorial.pdf** and it says to  "**Plug all the pins around the WiFi Module**" but it isn't very clear why and when should they be unplugged, I'll be getting my board tomorrow so I'm excited for the new challenge!!!

Thank you

**Comment by FLYmaker** [comment]
I will upload later
