### ISSUE TITLE
M997 S1 failed

### ISSUE THREAD

**Issue by DKXAM** [FLYmaker/FLY-CDY#2]
Hey

I did all the steps in the reprapfw guide and it keeps failing to connect after sending m997 s1, i did them exactly in the order described and then tried many different orders even unpluging the wifi jumpers, formatting the sd card differently, using a different sdcard etc etc

So far no luck, what else could it be?

**Comment by DKXAM** [comment]
>>> m997 s1
SENDING:M997 S1
Trying to connect at 230400 baud:
 failed
Trying to connect at 115200 baud:
 failed
Trying to connect at 74880 baud:
 failed
Trying to connect at 9600 baud:
 failed
Error: Installation failed due to comm write error
[ERROR] Error: Installation failed due to comm write error

**Comment by FLYmaker** [comment]
Sorry for the late reply today

**Comment by FLYmaker** [comment]
![_CG%`A NNSDBWDMG7(CMKBH](https://user-images.githubusercontent.com/49380822/100894204-34109300-34f7-11eb-8cdb-094e030522e4.png)
Please short-circuit this resistor

**Comment by FLYmaker** [comment]
Sorry for the late reply

**Comment by DKXAM** [comment]
hey, how do i do that? 

Solder it off and add a wire/solder blob?

**Comment by DKXAM** [comment]
okay, that worked! thanks

**Comment by DKXAM** [comment]
@FLYmaker so i soldered it of and added a wire, please tell me if that was correct or if i should put the resistor back

**Comment by FLYmaker** [comment]
Yes, this resistor is labeled wrong and forget to modify it, just short it

**Comment by FLYmaker** [comment]
I'm very sorry, I wish you a happy use, if you have any questions, please feel free to contact me

**Comment by Spanker-General** [comment]
So I need to buy a soldering iron

**Comment by FLYmaker** [comment]
> 所以我需要买烙铁

Only 3 motherboards have the wrong resistance value, so there is no need to buy a soldering iron. This resistance is only needed when burning the WIFI firmware. Neither turn on wifi nor turn off wifi need to go through this resistor

**Comment by Spanker-General** [comment]
So the fly-cdy should work without doing this change?

**Comment by archangel1982** [comment]
Hello @FLYmaker I just got my board in and doing some reading to learn so I can succesfully deploy it.  Are you stating here that if you want to flash the firmware for the FLY-CDY wifi, you must short that resistor ?

**Comment by FLYmaker** [comment]
> 您好，@ FLYmaker，我刚刚进入董事会，做了一些阅读学习，以便可以成功进行部署。您是否在这里说明，如果要为FLY-CDY wifi刷新固件，必须使该电阻短路？

No, only 3 motherboards are sent wrong, other motherboards are normal, no need to short circuit

**Comment by vldvirgil** [comment]
I just received my Octopus pro. Trying to flash the wifi card and am getting the same error stated previously. Exactly the same. Is this a problem with needing to short a resistor? Thank you in advance.

**Comment by jaysuk** [comment]
no. please join the teamgloomy discord for support https://discord.gg/uS97Qs7
