### ISSUE TITLE
Mistake in the use tuterial

### ISSUE THREAD

**Issue by DKXAM** [FLYmaker/FLY-CDY#3]
Dear Flymaker

I found a small mistake in the guide, nothing horrible but it could waste somebody's time 

The example text for the wifi config says
I send: M587 P"FLY2" S"12345678" as shown

it should be

I send: M587 S"FLY2" P"12345678" as shown

I also have some smaller things that could be made clearer in the guide for beginners

It tells you to plug the pins around the wifi module after you power on the board, this does not seem to be needed and is safer when done when the board it off

"Open the debuging software and select the port"
This is unclear for people who have never used pronterface before, include a link to the software and call it by its name

Thanks for the cool board, I think the layout is very good but will give more feedback after some more use

**Comment by FLYmaker** [comment]
Thank you, I have noticed it, and I haven't had time to modify it.

**Comment by Spanker-General** [comment]
@DXAM
Are you still using the board?
I'm having issues with my two boards unable to write, connection issues, connects then drops, then jumps to different com port, connects then drops, not able to input SSID and password.
Can advise re WiFi pin please explain

**Comment by DKXAM** [comment]
@Spanker-General 

No issues my board has been working great with RRF and the LPC port with the updated wifi drivers. Pronterface lower case trick did not work for me so i had to change my ssid and pw to full caps in order to connect to the wifi easily. Did you see the trick with soldering off the resistors that flymaker told me to do in the other issue? Maybe you also need that, although I have no idea if that is correct so please double check with @FLYmaker for that.

**Comment by Spanker-General** [comment]
@DKXAM Can you just use short on the pins?
Appreciate the reply by the way

**Comment by DKXAM** [comment]
@Spanker-General i just soldered it off and soldered on a tiny wire as i had no idea how to do it in another way, there seemed to be a 10k resistor there. Any sort of short should work i guess, less permanent versions as well.

**Comment by Spanker-General** [comment]
Thank you @DKXAM
