### ISSUE TITLE
Unable to read or write Fly-Cdy

### ISSUE THREAD

**Issue by Spanker-General** [FLYmaker/FLY-CDY#4]
Installed a board with software but am no longer able to connect via Linux os through usb via Pronterface.
Any help or advice deeply appreciated

Connecting...
[ERROR] Can't read from printer (disconnected?) (SerialException): device reports readiness to read but returned no data (device disconnected or multiple access on port?)
[ERROR] Can't write to printer (disconnected?) (SerialException): write failed: [Errno 5] Input/output error
[ERROR] Can't read from printer (disconnected?) (SerialException): device reports readiness to read but returned no data (device disconnected or multiple access on port?)
[ERROR] Can't write to printer (disconnected?) (SerialException): write failed: [Errno 5] Input/output error
[ERROR] Can't read from printer (disconnected?) (SerialException): device reports readiness to read but returned no data (device disconnected or multiple access on port?)
[ERROR] Can't write to printer (disconnected?) (SerialException): write failed: [Errno 5] Input/output error
[ERROR] Can't read from printer (disconnected?) (SerialException): device reports readiness to read but returned no data (device disconnected or multiple access on port?)
[ERROR] Can't write to printer (disconnected?) (SerialException): write failed: [Errno 5] Input/output error
[ERROR] Aborting connection attempt after 4 failed writes.
[ERROR] Can't read from printer (disconnected?) (SerialException): device reports readiness to read but returned no data (device disconnected or multiple access on port?)
Connecting...
[ERROR] Could not connect to /dev/ttyACM0 at baudrate 250000:
Serial error: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
Connecting...
[ERROR] Can't read from printer (disconnected?) (SerialException): device reports readiness to read but returned no data (device disconnected or multiple access on port?)
[ERROR] Can't write to printer (disconnected?) (SerialException): write failed: [Errno 5] Input/output error
[ERROR] Can't read from printer (disconnected?) (SerialException): device reports readiness to read but returned no data (device disconnected or multiple access on port?)
[ERROR] Can't write to printer (disconnected?) (SerialException): write failed: [Errno 5] Input/output error
[ERROR] Can't read from printer (disconnected?) (SerialException): device reports readiness to read but returned no data (device disconnected or multiple access on port?)
[ERROR] Can't write to printer (disconnected?) (SerialException): write failed: [Errno 5] Input/output error
[ERROR] Can't read from printer (disconnected?) (SerialException): device reports readiness to read but returned no data (device disconnected or multiple access on port?)
[ERROR] Can't write to printer (disconnected?) (SerialException): write failed: [Errno 5] Input/output error
[ERROR] Aborting connection attempt after 4 failed writes.
[ERROR] Can't read from printer (disconnected?) (SerialException): device reports readiness to read but returned no data (device disconnected or multiple access on port?)
Connecting...
[ERROR] Can't read from printer (disconnected?) (SerialException): device reports readiness to read but returned no data (device disconnected or multiple access on port?)
[ERROR] Can't write to printer (disconnected?) (SerialException): write failed: [Errno 5] Input/output error
[ERROR] Can't read from printer (disconnected?) (SerialException): device reports readiness to read but returned no data (device disconnected or multiple access on port?)
[ERROR] Can't write to printer (disconnected?) (SerialException): write failed: [Errno 5] Input/output error
[ERROR] Can't read from printer (disconnected?) (SerialException): device reports readiness to read but returned no data (device disconnected or multiple access on port?)
[ERROR] Can't write to printer (disconnected?) (SerialException): write failed: [Errno 5] Input/output error
[ERROR] Can't read from printer (disconnected?) (SerialException): device reports readiness to read but returned no data (device disconnected or multiple access on port?)
[ERROR] Can't write to printer (disconnected?) (SerialException): write failed: [Errno 5] Input/output error
[ERROR] Aborting connection attempt after 4 failed writes.
[ERROR] Can't read from printer (disconnected?) (SerialException): device reports readiness to read but returned no data (device disconnected or multiple access on port?)
Connecting...
Loading LPC config from 0:/sys/board.txt...
Checking drivers...
Driver 0 ready
Driver 1 ready
Driver 2 ready
Driver 3 ready
RepRapFirmware for LPC176x based Boards version 3.2-beta2_5
Executing config.g... ok
HTTP is enabled on port 80
FTP is disabled
TELNET is disabled
Done!
Executing runonce.g...
Turn off the current WiFi mode before selecting a new one
[ERROR] Can't read from printer (disconnected?) (SerialException): device reports readiness to read but returned no data (device disconnected or multiple access on port?)
[ERROR] Can't write to printer (disconnected?) (SerialException): write failed: [Errno 5] Input/output error
[ERROR] Can't read from printer (disconnected?) (SerialException): device reports readiness to read but returned no data (device disconnected or multiple access on port?)
[ERROR] Can't write to printer (disconnected?) (SerialException): write failed: [Errno 5] Input/output error
[ERROR] Can't read from printer (disconnected?) (SerialException): device reports readiness to read but returned no data (device disconnected or multiple access on port?)
[ERROR] Can't write to printer (disconnected?) (SerialException): write failed: [Errno 5] Input/output error
[ERROR] Can't read from printer (disconnected?) (SerialException): device reports readiness to read but returned no data (device disconnected or multiple access on port?)
[ERROR] Can't write to printer (disconnected?) (SerialException): write failed: [Errno 5] Input/output error
[ERROR] Aborting connection attempt after 4 failed writes.
[ERROR] Can't read from printer (disconnected?) (SerialException): device reports readiness to read but returned no data (device disconnected or multiple access on port?)
Connecting...
[ERROR] Could not connect to /dev/ttyACM1 at baudrate 250000:
Serial error: [Errno 2] could not open port /dev/ttyACM1: [Errno 2] No such file or directory: '/dev/ttyACM1'
Reset.
Connecting...
[ERROR] Could not connect to /dev/ttyACM1 at baudrate 250000:
Serial error: [Errno 2] could not open port /dev/ttyACM1: [Errno 2] No such file or directory: '/dev/ttyACM1'
Connecting...
[ERROR] Can't read from printer (disconnected?) (SerialException): device reports readiness to read but returned no data (device disconnected or multiple access on port?)
[ERROR] Can't write to printer (disconnected?) (SerialException): write failed: [Errno 5] Input/output error
[ERROR] Can't read from printer (disconnected?) (SerialException): device reports readiness to read but returned no data (device disconnected or multiple access on port?)
[ERROR] Can't write to printer (disconnected?) (SerialException): write failed: [Errno 5] Input/output error
[ERROR] Can't read from printer (disconnected?) (SerialException): device reports readiness to read but returned no data (device disconnected or multiple access on port?)
[ERROR] Can't write to printer (disconnected?) (SerialException): write failed: [Errno 5] Input/output error
[ERROR] Can't read from printer (disconnected?) (SerialException): device reports readiness to read but returned no data (device disconnected or multiple access on port?)
[ERROR] Can't write to printer (disconnected?) (SerialException): write failed: [Errno 5] Input/output error
[ERROR] Aborting connection attempt after 4 failed writes.
[ERROR] Can't read from printer (disconnected?) (SerialException): device reports readiness to read but returned no data (device disconnected or multiple access on port?)

**Comment by Spanker-General** [comment]
Second attempt this morning

Connecting...
Loading LPC config from 0:/sys/board.txt...
Checking drivers...
Driver 0 ready
Driver 1 ready
Driver 2 ready
Driver 3 ready
RepRapFirmware for LPC176x based Boards version 3.2-beta2_5
Executing config.g... ok
HTTP is enabled on port 80
FTP is disabled
TELNET is disabled
Done!
Executing runonce.g...
Turn off the current WiFi mode before selecting a new one
[ERROR] Can't read from printer (disconnected?) (SerialException): device reports readiness to read but returned no data (device disconnected or multiple access on port?)
[ERROR] Can't write to printer (disconnected?) (SerialException): write failed: [Errno 5] Input/output error
[ERROR] Can't read from printer (disconnected?) (SerialException): device reports readiness to read but returned no data (device disconnected or multiple access on port?)
[ERROR] Can't write to printer (disconnected?) (SerialException): write failed: [Errno 5] Input/output error
[ERROR] Can't read from printer (disconnected?) (SerialException): device reports readiness to read but returned no data (device disconnected or multiple access on port?)
[ERROR] Can't write to printer (disconnected?) (SerialException): write failed: [Errno 5] Input/output error
[ERROR] Can't read from printer (disconnected?) (SerialException): device reports readiness to read but returned no data (device disconnected or multiple access on port?)
[ERROR] Can't write to printer (disconnected?) (SerialException): write failed: [Errno 5] Input/output error
[ERROR] Aborting connection attempt after 4 failed writes.
[ERROR] Can't read from printer (disconnected?) (SerialException): device reports readiness to read but returned no data (device disconnected or multiple access on port?)

**Comment by FLYmaker** [comment]
[firmware.zip](https://github.com/FLYmaker/FLY-CDY/files/5708734/firmware.zip)

**Comment by FLYmaker** [comment]
Please burn this program

**Comment by Spanker-General** [comment]
Have burnt it but still getting this error

Connecting...
ok T0:-273.1 /0.0 B:-273.1 /0.0
Printer is now online.
[ERROR] Can't read from printer (disconnected?) (SerialException): device reports readiness to read but returned no data (device disconnected or multiple access on port?)
[ERROR] Can't write to printer (disconnected?) (SerialException): write failed: [Errno 5] Input/output error

**Comment by FLYmaker** [comment]
Have you tried other computers?

**Comment by FLYmaker** [comment]
Or other usb port

**Comment by Spanker-General** [comment]
Have tried both boards on my spare lap top both having the same issues of connecting disconnecting on windows and linux
I have checked wiring and wires and connectors check out in the correct positions too. Not sure what else to try next

**Comment by Spanker-General** [comment]
Edit windows pronterface kept sending M105 with no response checked thermistors and they are located correctly

**Comment by FLYmaker** [comment]
Delete the M552 S1 content in config.g

**Comment by FLYmaker** [comment]
Send your config content

**Comment by Spanker-General** [comment]
Are you asking for a copy of the config.g file?

**Comment by Spanker-General** [comment]
; Configuration file for Fly-CDY (firmware version 3)
; executed by the firmware on start-up
;
; generated by RepRapFirmware Configuration Tool v3.1.10-LPC on Wed Dec 16 2020 09:04:14 GMT+0000 (Greenwich Mean Time)

; General preferences
G90                                            ; send absolute coordinates...
M83                                            ; ...but relative extruder moves
M550 P"Aaron's Anet A8"                        ; set printer name

; Network
                                       ; enable network
M586 P0 S1                                     ; enable HTTP
M586 P1 S0                                     ; disable FTP
M586 P2 S0                                     ; disable Telnet

; Drives
M569 P0 S1                                     ; physical drive 0 goes forwards using default driver timings
M569 P1 S0                                     ; physical drive 1 goes backwards using default driver timings
M569 P2 S1                                     ; physical drive 2 goes forwards using default driver timings
M569 P3 S1                                     ; physical drive 3 goes forwards using default driver timings
M584 X0 Y1 Z2 E3                               ; set drive mapping
M350 X16 Y16 Z16 E16 I1                        ; configure microstepping with interpolation
M92 X80.00 Y80.00 Z400.00 E420.00              ; set steps per mm
M566 X900.00 Y900.00 Z12.00 E120.00            ; set maximum instantaneous speed changes (mm/min)
M203 X6000.00 Y6000.00 Z180.00 E1200.00        ; set maximum speeds (mm/min)
M201 X500.00 Y500.00 Z20.00 E250.00            ; set accelerations (mm/s^2)
M906 X800 Y800 Z800 E800 I30                   ; set motor currents (mA) and motor idle factor in per cent
M84 S30                                        ; Set idle timeout

; Axis Limits
M208 X0 Y0 Z0 S1                               ; set axis minima
M208 X300 Y300 Z350 S0                         ; set axis maxima

; Endstops
M574 X1 S1 P"xstop"                            ; configure active-high endstop for low end on X via pin xstop
M574 Y1 S1 P"ystop"                            ; configure active-high endstop for low end on Y via pin ystop

; Z-Probe
M558 P0 H5 F120 T6000                          ; disable Z probe but set dive height, probe speed and travel speed
M557 X15:215 Y15:195 S20                       ; define mesh grid

; Heaters
M308 S0 P"bedtemp" Y"thermistor" T100000 B4138 ; configure sensor 0 as thermistor on pin bedtemp
M950 H0 C"bed" T0                              ; create bed heater output on bed and map it to sensor 0
M307 H0 B0 S1.00                               ; disable bang-bang mode for the bed heater and set PWM limit
M140 H0                                        ; map heated bed to heater 0
M143 H0 S120                                   ; set temperature limit for heater 0 to 120C
M143 H0 S120                                   ; set temperature limit for heater 0 to 120C
M308 S1 P"e0temp" Y"thermistor" T100000 B4138  ; configure sensor 1 as thermistor on pin e0temp
M950 H1 C"e0heat" T1                           ; create nozzle heater output on e0heat and map it to sensor 1
M307 H1 B0 S1.00                               ; disable bang-bang mode for heater  and set PWM limit
M143 H1 S280                                   ; set temperature limit for heater 1 to 280C

; Fans
M950 F0 C"fan0" Q500                           ; create fan 0 on pin fan0 and set its frequency
M106 P0 S0 H-1                                 ; set fan 0 value. Thermostatic control is turned off

; Tools
M563 P0 D0 H1 F0                               ; define tool 0
G10 P0 X0 Y0 Z0                                ; set tool 0 axis offsets
G10 P0 R0 S0                                   ; set initial tool 0 active and standby temperatures to 0C

; Custom settings are not defined

**Comment by Spanker-General** [comment]
Have deleted the line M552 as requested, the boards still threw up the error previously mentioned.

**Comment by Spanker-General** [comment]
Update, got the boards stable but having trouble burning wifi bin file

**Comment by FLYmaker** [comment]
[DuetWiFiServer.zip](https://github.com/FLYmaker/FLY-CDY/files/5710131/DuetWiFiServer.zip)

**Comment by FLYmaker** [comment]
Put this file into the sys folder

**Comment by Spanker-General** [comment]
I am still not able to do this setup, I have read something on gloomyandy post apparently I need to connect an esp tool and use that to burn the firmware to it, is that corrrect?

**Comment by FLYmaker** [comment]
No need, decompress the file I sent to you, put the .bin file into the sd card, and use M997 S1 to command the motherboard to automatically burn the wifi program

**Comment by Spanker-General** [comment]
I have done that, it brings up an error can't write and disconnects the board

**Comment by FLYmaker** [comment]
Take a picture of your motherboard

**Comment by Spanker-General** [comment]
Will do

**Comment by Spanker-General** [comment]
Will this image be enough?

**Comment by Spanker-General** [comment]
Not able to upload an image

**Comment by FLYmaker** [comment]
Drag the picture to the input window

**Comment by Spanker-General** [comment]
Trying now, have had to use my main pc as mobile will not let me drag and drop into github,

**Comment by Spanker-General** [comment]
/home/Aaron/Downloads/IMG_20201218_075724_5.jpg

I am hoping this is clear enough and works

**Comment by FLYmaker** [comment]
https://discord.gg/hccjyvv

**Comment by FLYmaker** [comment]
Use this, you can contact in real time
