### ISSUE TITLE
UART mode pin arrangement.

### ISSUE THREAD

**Issue by maszi1978** [FLYmaker/FLY-CDY#5]
Hi,
Would it be possible to upload an image showing how the jumpers are set for 6 X TMC drivers?  I am upgrading from a board where the drivers were just plug and play so it would help me a lot.
Thanks

**Comment by FLYmaker** [comment]
![Uploading image.png…]()

**Comment by FLYmaker** [comment]
![image](https://user-images.githubusercontent.com/49380822/103448790-67eafe00-4cd9-11eb-933e-5eaa035ad9b7.png)

**Comment by maszi1978** [comment]
Thanks for the quick reply, however it did not answer my question. Which one is the correct connection on the image below? Thanks
![Untitled](https://user-images.githubusercontent.com/16231609/103454700-88698700-4cde-11eb-93c9-19808ab0d90e.jpg)

**Comment by c1000mg** [comment]
The first image is the correct
