### ISSUE TITLE
BL Touch pin

### ISSUE THREAD

**Issue by mwalter665** [FLYmaker/FLY-CDY#6]
Hello, i have same questions for the BL Touch:

![image](https://user-images.githubusercontent.com/80543660/111263861-d4ae3d00-8626-11eb-8399-9672b85357b9.png)

here are only three pins at this layout

![image](https://user-images.githubusercontent.com/80543660/111263932-f60f2900-8626-11eb-829d-f67b551cf241.png)

Here ist the backside with zmin and 5 Pins, does this mean:

![image](https://user-images.githubusercontent.com/80543660/111264060-2c4ca880-8627-11eb-9ad7-97c419d7bfb6.png)

that this two pins are the same like z-min? But Z-Min has three pins - this are only two pins

In the pinout is the number of BL Touch and z-min the same:

![image](https://user-images.githubusercontent.com/80543660/111264338-9c5b2e80-8627-11eb-88fb-02d3dcbdfbe4.png)

So i have to activate:

![image](https://user-images.githubusercontent.com/80543660/111264472-df1d0680-8627-11eb-8d64-87130bf3ef90.png)

is this correct? And it is not possible to use a security seperat mechnical z-min?

Thanks and having a fine day.

**Comment by jaysuk** [comment]
yes, they use the same pin.
if you want a bltouch and minimum z endstop, you'll have to use a different input for the bltouch or the endstop
