### ISSUE TITLE
Dual-Z-Axis Homing

### ISSUE THREAD

**Issue by AndylgTom** [FLYmaker/FLY-CDY#7]
Question about Dual-Z-Endstops (when using two Z endstops and two drivers )

Can I do this?
Can you add it to the RepRapFirmware Configuration Tool?

Motherboard FLY-CDY V2.

**Comment by FLYmaker** [comment]
M569 P0 S0                                   ; physical drive 0 goes backwards using default driver timings
M569 P1 S0                                    ; physical drive 1 goes backwards using default driver timings
M569 P2 S1                                    ; physical drive 2 goes forwards using default driver timings
M569 P3 S0                                                ; physical drive 3 goes forwards using default driver timings
M569 P4 S0
M584 X0 Y1 Z2:4 E3                               ;X Y Z E0 Z2
M574 Z1 S1 P"zstop+zstopmax" ;

**Comment by AndylgTom** [comment]
Is that all? What about "Endstops"? 
You can share an example of a full config.g for this case?
I don't fully understand.
